#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.6.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that run after cloning repository
install:
  #Download AutoHotkey Compiler
  - ps: Invoke-WebRequest "http://ahkscript.org/download/ahk2exe.zip" -OutFile "$pwd\ahk2exe.zip"
  #Unzip it!
  - ps: Invoke-Expression "7z e ahk2exe.zip"

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - Ahk2Exe.exe /in mDesktop.ahk /out mDesktop.exe /icon mDesktop.ico > status.txt

# to disable automatic builds
build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
 - ps: $status = Get-Content "status.txt"
 - ps: Add-AppveyorCompilationMessage $status -Category Information -FileName "Ahk2Exe.exe"
 - ps: if ("Successfully compiled: mDesktop.exe" -like $status)
 - ps: { 
 - ps:     $zip="mDesktop.$env:APPVEYOR_BUILD_VERSION.zip"
 -         7z a $zip mDesktop.exe
 -         7z a $zip Win.ahk
 -         7z a $zip License.txt
 -         7z a $zip icons\
 - ps:     Push-AppveyorArtifact "$zip"
 - ps:     Add-AppveyorTest "Build" -Outcome Passed -StdOut $status -Framework xUnit -FileName Ahk2Exe.exe
 - ps: }
 - ps: else
 - ps: {
 - ps:    Add-AppveyorTest "Build" -Outcome Failed -StdOut $status -Framework xUnit -FileName Ahk2Exe.exe
 - ps: }

# to disable automatic tests 
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: mDesktop{version}.zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: FTP
    server: ftp.phx.nearlyfreespeech.net
    username: octalmage_mdesktop
    password: {password}
    folder: build
